config/routes.rb
require 'api'
Gohike::Application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    get "state_province_list", :to => "cities#states_or_provinces"

    get '/translation/:resource_type/:resource_id(/:target_locale)', :to => "translations#new", :as => :translation

    get "start", :to => "start#index"

    get "home", :to => "home#index"

    resources :routes do
      resource :reward
      member do
        put :waypoints
        get :crop
        put :publish
        put :unpublish
      end
    end
    resources :rewards
    resources :checkins

    resources :cities do
      resources :route_profiles
      resources :locations do
        collection do
          get :search
        end
      end
    end

    resources :route_profiles do
      collection do
        get :in_cities
      end
      member do
        get :crop
      end

    end
    resources :locations do
      member do
        get :crop
      end

    end
    resources :devices
    devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}

  end
  mount Gohike::API => "/api"

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  MIN_WIDTH = 480
  MIN_HEIGHT = 480
  mount_uploader :image, RewardUploader
  belongs_to :route

  attr_accessible :description, :image, :name, :route_id, :translations_attributes

  translates :name, :description, :fallbacks_for_empty_translations => true
  accepts_nested_attributes_for :translations


  validate :validate_image_size_and_ratio
  validates_presence_of :name, :description, :route_id

  class Translation
    attr_accessible :locale, :name, :description
    validates_presence_of :name, :description
  end

  def image_data
    Base64.encode64(open(self.image.to_s) { |io| io.read }) unless self.image.to_s.blank?
  end

  def validate_image_size_and_ratio
    unless image.blank?
      if image.file.respond_to?(:sanitize_regexp)
        img = MiniMagick::Image.read(image.file)
      else

        img = MiniMagick::Image.open(image.url)
      end
      unless (img[:width] >= MIN_WIDTH && img[:height] >= MIN_HEIGHT) && (img[:width]/img[:height] == 1)
        errors.add :image, :image_minimum_size, :min_width => MIN_WIDTH, :min_height => MIN_HEIGHT
      end
    end
  end
end

app/controllers/rewards_controller.rb
class RewardsController < InheritedResources::Base
  layout Proc.new { |controller| (controller.request.xhr? || controller.remotipart_submitted?) ? false : 'application' }
  respond_to :js, :json, :html
  before_filter :authenticate_user!, :except => :show
  defaults :singleton => true

  optional_belongs_to :route
  #optional_belongs_to :route_profile

  #load_and_authorize_resource :route_profile, :through => :route
  load_and_authorize_resource :route, :through => :reward
  load_and_authorize_resource :reward

  def build_resource
    super
  end


  def resource
    if params[:id].blank?
      @reward ||= association_chain[0].reward
    else
      @reward = Reward.find(params[:id])
    end
  end

  def edit
    super
  end

  def show
    super do |format|
      format.html {
        if request.xhr?
          render :partial => 'routes/reward'
        else
          render layout: "reward"
        end

      } # show.html.erb
      format.json { render json: @reward }
    end
  end

  def destroy
    resource.destroy
    respond_to do |format|
      format.html { head :ok }
      format.json { head :no_content }
    end
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= simple_form_for([@route, @reward], :url=> route_reward_path(@route), :remote => true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs clearfix">
    <div class="span5">

      <%= f.input :image %>
    </div>
    <div class="span5">

      <%= render :partial => "shared/localized_attributes", :locals => {:resource => @reward, :f => f}  %>

    </div>

  </div>

  <div class="form-actions hidden">
    <%= f.button :submit %>
  </div>


<% end %>

app/views/rewards/create.js.erb
<% if remotipart_submitted? %>
   console.log("done");
<% else %>
  console.log("boooj");
<% end %>

app/views/rewards/edit.html.erb
<%= render 'form' %>

app/views/rewards/index.html.erb
<h1>Listing rewards</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Image</th>
    <th>Rewardable type</th>
    <th>Rewardable</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rewards.each do |reward| %>
  <tr>
    <td><%= reward.name %></td>
    <td><%= reward.description%></td>
    <td><%= reward.image %></td>
    <td><%= reward.rewardable_type %></td>
    <td><%= reward.rewardable_id %></td>
    <td><%= link_to 'Show', reward %></td>
    <td><%= link_to 'Edit', edit_reward_path(reward) %></td>
    <td><%= link_to 'Destroy', reward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reward', new_reward_path %>

app/views/rewards/new.html.erb
<%= render 'form' %>

app/views/rewards/show.html.erb
<div class="rewards-container-narrow">

  <div class="masthead">

  </div>

  <hr>

  <div class="rewards-jumbotron">
    <h1><%= @reward.name%> </h1>
    <p class="lead">
      <img style="width: 400px; height: 400px;" src="<%= @reward.image %>">
    </p>
    <p class="lead">  <%= @reward.description %></p>
  </div>
  <hr>
  <p class="lead centered">Take a Hike!</p>
  <div class="row-fluid rewards-marketing">
    <div class="span6">
      <p class="centered">
        <a href="https://itunes.apple.com/nl/app/take-a-hike!/id659545032?l=en&mt=8" target="_blank">
          <%= image_tag("Available_on_the_App_Store_Badge_172.png")%></a>
      </p>
      </div>
    <div class="span6">
      <p class="centered">
        <a href="#" target="_blank">
          <%= image_tag("en_generic_rgb_wo_172.png")%></a>
      </p>

    </div>


  </div>

  <div class="footer-center">

  </div>

</div>



<% content_for :reward_meta do %>
  <meta property="og:title" content="<%= @reward.name %>">
  <meta property="og:url" content="<%= reward_path(@reward) %>">
  <meta property="og:description" content="<%= @reward.description %>">
  <meta property="og:image" content="<%= @reward.image_url %>">
  <meta property="game:points" content="5">
  <meta property="fb:app_id" content="547542925309510">
<% end %>

app/views/rewards/update.js.erb
<% if remotipart_submitted? %>
   console.log("done");
<% else %>
  console.log("booo");
<% end %>