config/routes.rb
require 'api'
Gohike::Application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    get "state_province_list", :to => "cities#states_or_provinces"

    get '/translation/:resource_type/:resource_id(/:target_locale)', :to => "translations#new", :as => :translation

    get "start", :to => "start#index"

    get "home", :to => "home#index"

    resources :routes do
      resource :reward
      member do
        put :waypoints
        get :crop
        put :publish
        put :unpublish
      end
    end
    resources :rewards
    resources :checkins

    resources :cities do
      resources :route_profiles
      resources :locations do
        collection do
          get :search
        end
      end
    end

    resources :route_profiles do
      collection do
        get :in_cities
      end
      member do
        get :crop
      end

    end
    resources :locations do
      member do
        get :crop
      end

    end
    resources :devices
    devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}

  end
  mount Gohike::API => "/api"

end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :country_code, :latitude, :longitude, :name, :radius, :state_province, :top_left_lat, :top_left_lon, :bottom_right_lat, :bottom_right_lon
  validates_presence_of :name, :radius, :country_code, :state_province
  validates_uniqueness_of :name, :scope => [:country_code, :state_province], :case_sensitive => false

  acts_as_gmappable :process_geocoding => true, :lat => "latitude", :lng => "longitude"

  #has_many :roles, :as => :authorizable
  #has_many :route_profiles
  has_many :locations
  has_many :routes
  has_many :route_profiles


  def gmaps4rails_address
    #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    fullname
  end

  def country_name
    Carmen::Country.coded(country_code).name
  end

  def fullname
    if country_code == "US"
      "#{self.name.camelize}," + (self.state_province.present? ? " #{self.state_province}" : "")
    else
      "#{self.name.camelize},"  +" #{self.country_name}"
      #+ (self.state_province.present? ? " #{self.state_province}," : "")
    end

  end

  def self.by_device_location(latitude, longitude)
     self.where("top_left_lat >= #{latitude} and top_left_lon <= #{longitude} AND bottom_right_lat <= #{latitude} and bottom_right_lon >= #{longitude}")
  end

  def publishable_profiles
    route_profiles.all(:joins => :routes,
        :conditions => "routes.published_key IS NOT NULL",
        :group => 'route_profiles.id',
        :order => 'priority',
        :having => "count(routes.id) > 0")
  end

  def self.with_publishable_profiles
    cities = []
    self.find_each do |city|
      if (city.publishable_profiles.count > 0)
        cities << city
      end
    end
    return cities
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource


  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
    @json = City.all.to_gmaps4rails do |city, marker|
      marker.json({:id => city.id, :foo => city.name})
    end
    @circles_json = City.all.to_gmaps4rails do |city, circle|
      circle.json({:lat => city.latitude, :lon => city.longitude, :radius => city.radius * 1000})
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cities }
    end
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @city = City.find(params[:id])
    @json = @city.to_gmaps4rails   do |city, marker|
      marker.json({:id => city.id, :foo => city.name})
    end

    @circles_json = @city.to_gmaps4rails do |city, circle|
      circle.json({:lat => city.latitude, :lon => city.longitude, :radius => city.radius * 1000})
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/new
  # GET /cities/new.json
  def new
    @city = City.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/1/edit
  def edit
    @city = City.find(params[:id])
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(params[:city])

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render json: @city, status: :created, location: @city }
      else
        format.html { render action: "new" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cities/1
  # PUT /cities/1.json
  def update
    @city = City.find(params[:id])

    respond_to do |format|
      if @city.update_attributes(params[:city])
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city = City.find(params[:id])
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end

  def states_or_provinces
    render :partial => "state", :locals => {:country_code => params[:country_code]}
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= simple_form_for(@city) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs clearfix">
    <div class="span5">
      <%= f.input :country_code, :label => t(:country) do %>
        <%= f.country_select :country_code, {priority: %w(NL), :include_blank => true}, {object: f.object, prompt: 'Please select a country'} %>
      <% end %>
      <%= f.input :state_province, :label => t(:state_or_province), :wrapper_html => {:class => ("hidden" if @city.state_province.blank?)} do %>
        <%= render partial: 'state', locals: {country_code: f.object.country_code} %>
      <% end %>
      <div>
        <%= f.input :name %>
      </div>
      <div></div>

      <div>
        <%= f.input :latitude, :input_html => {:readonly => true} %>
        <%= f.input :longitude, :input_html => {:readonly => true} %>
        <%= f.input :top_left_lat, :as => :hidden %>
        <%= f.input :top_left_lon, :as => :hidden %>
        <%= f.input :bottom_right_lat, :as => :hidden %>
        <%= f.input :bottom_right_lon, :as => :hidden %>
        <%= f.input :radius, :hint => "Radius is shown in Kilometers" %>
      </div>
    </div>
    <div class="span4">
      <% options = {
          :map_options => {
              :auto_adjust => true,
              zoomControl: true,
              zoom: 10,
              streetViewControl: false,
              scaleControl: false,
              rotateControl: false,
              mapTypeControl: false,
              panControl: false,
              center_latitude: @city.latitude,
              center_longitude: @city.longitude,
              draggable: false
          },
          :circles => {:data => []},
          :markers => {:data => [], :options => {:do_clustering => true}}

      }
      %>
      <%= gmaps(options) %>
    </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<% content_for :scripts do %>
  <script>
    var buffer_circle = null;
    var map_marker = null;


    Gmaps.map.callback = function () {
      console.log("callback", arguments);
      var map = Gmaps.map.map,
          geocoder = new google.maps.Geocoder(),
          crosshairShape = {coords: [0, 0, 0, 0], type: 'rect'},
          marker, mapReady = false;


      <% if @city.new_record? %>
      setDefaultMapCenter(map);
      <% else %>
      createCircle(<%=@city.latitude %>, <%= @city.longitude %>, <%= @city.radius %>);
      setMarker(<%=@city.latitude %>, <%= @city.longitude %>);

      <% end %>


      google.maps.event.addListener(map, 'tilesloaded', function () {
//        console.log("tiles loaded")
      });

      google.maps.event.addListener(map, 'center_changed', function () {
//        console.log("center_changed");
      });
      google.maps.event.addListener(map, 'zoom_changed', function () {
//        console.log("zoom_changed");

      });

      google.maps.event.addListener(map, 'idle', function () {
//        console.log("idle");


        if (mapReady) {
          console.log("go")

        }
        mapReady = true;
      });
    };

    setDefaultMapCenter = function (map) {
      var geocoder = new google.maps.Geocoder();
      geocoder.geocode({address: "Amsterdam, Netherlands"}, function (results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          result = results[0];
          if (result) {
            map.setCenter(result.geometry.location);

            var rad = $("#city_radius").val();
            createCircle(result.geometry.location.hb, result.geometry.location.ib, rad);
            setMarker(result.geometry.location.hb, result.geometry.location.ib);
          }
        }
      });
    }

    window.setMapCenter = function (addressToGeocode) {
      map = Gmaps.map.map;
      var geocoder = new google.maps.Geocoder();
      geocoder.geocode({address: addressToGeocode}, function (results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          result = results[0];
          if (result) {
            map.setCenter(result.geometry.location);
            var rad = $("#city_radius").val();
            $("#city_latitude").val(result.geometry.location.lat());
            $("#city_longitude").val(result.geometry.location.lng());

            createCircle(result.geometry.location.hb, result.geometry.location.ib, rad);
            setMarker(result.geometry.location.hb, result.geometry.location.ib);
          }
        }
      });

    }

    window.setMarker = function (lat, lon, map) {
      if (map == null) {
        map = Gmaps.map.map;
      }
      if (map_marker != null) {
        map_marker.setMap(null);
      }

      map_marker = new google.maps.Marker(
          {
            map: map,
            position: new google.maps.LatLng(lat, lon)
          }
      );
    }

    // Draw circle with radius
    window.createCircle = function (lat, lon, rad, map) {
      rad *= 1000; // convert to meters if in miles
      if (map == null) {
        map = Gmaps.map.map;
      }

      if (buffer_circle != null) {
        buffer_circle.setMap(null);
      }

      buffer_circle = new google.maps.Circle({
        center: new google.maps.LatLng(lat, lon),
        radius: rad,
        strokeColor: "",
        strokeOpacity: 0.0,
        strokeWeight: 2,
        fillColor: "#ADFF2F",
        fillOpacity: 0.5,
        map: map
      });

      getSquareForCity(lat, lon, rad);

    }

    window.getSquareForCity = function (lat, lon, rad) {
      var cityLatLng = new google.maps.LatLng(lat, lon);
      var spherical = google.maps.geometry.spherical;
      var north = spherical.computeOffset(cityLatLng, rad, 0);
      var west = spherical.computeOffset(cityLatLng, rad, -90);
      var south = spherical.computeOffset(cityLatLng, rad, 180);
      var east = spherical.computeOffset(cityLatLng, rad, 90);
      $("#city_top_left_lat").val(north.lat());
      $("#city_top_left_lon").val(west.lng());
      $("#city_bottom_right_lat").val(south.lat());
      $("#city_bottom_right_lon").val(east.lng());


      console.log(north);
      console.log(east);

    }
  </script>
<% end %>

app/views/cities/_map.html.erb
<div class="span4">
  <%= gmaps("map_options" => {"detect_location" => false, "center_on_user" => false, "zoom" => 5},
            "circles" => {"data" => @circles_json, "options" => {"fillColor" => "#FF0000"}},
            "markers" => {"data" => @json, "options" => {"do_clustering" => true}
            }) %>

  <% content_for :scripts do %>
    <script type="text/javascript">
      Gmaps.map.callback = function () {
        //your code
        $(document).trigger('map:ready');
      }
    </script>
  <% end %>
</div>

app/views/cities/_state.html.erb
<% country_code ||= params[:city] ? params[:city][:country_code] : nil %>
<% country = Carmen::Country.coded(country_code) unless country_code.nil? %>
<% if !country.nil? and country.subregions? %>
  <%= subregion_select :city, :state_province, country_code ,{ :include_blank => true }, :label => "State/Province" %>
<% end %>

app/views/cities/edit.html.erb
<ul class="breadcrumb">
  <li><%= link_to t(:home), home_path %> <span class="divider">/</span></li>
  <li><%= link_to t(:'navbar.cities'), cities_path %> <span class="divider">/</span></li>
  <li class="active"><%= @city.name %></li>
</ul>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<%- model_class = City -%>
<ul class="breadcrumb">
  <li><%= link_to t(:home), home_path %> <span class="divider">/</span></li>
  <li class="active"><%= t(:'navbar.cities') %></li>
  <% if can? :read, RouteProfile %>
    <li class="pull-right"><%= link_to t(:profiles), route_profiles_path, :class => "profiles btn btn-mini btn-primary pull-right" %></li>

  <% end %>
  <% if can? :create, City %>
    <li class="pull-right"><%= link_to t(:add_city), new_city_path, :class => "add-city btn btn-mini btn-success pull-right" %></li>

  <% end %>
</ul>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:state_province) %></th>
    <th><%= model_class.human_attribute_name(:country_code) %></th>
    <th></th>

  </tr>
  </thead>
  <% @cities.each do |city| %>
    <tr>
      <td><%= city.name %></td>
      <td><%= city.state_province %></td>
      <td><%= city.country_code %></td>
      <td>
        <%= link_to t(:details), city_path(city), :class => "btn btn-mini" %>

        <% if can? :update, city %>
          <%= link_to t(:edit), edit_city_path(city), :class => "btn btn-mini btn-primary" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<br/>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to t(:home), home_path %> <span class="divider">/</span></li>
  <li><%= link_to t(:'navbar.cities'), cities_path %> <span class="divider">/</span></li>
  <li class="active"><%= @city.name %></li>
  <% if can? :read, RouteProfile %>
    <li class="pull-right"><%= link_to t(:profiles) + " in " +  @city.name.html_safe, route_profiles_path(:in_city => @city.id), :class => "profiles btn btn-mini btn-primary pull-right" %></li>
  <% end %>
</ul>
<div class="row">
  <div class="span4">
    <h4><%= t :details %>
      <% if can? :update, @city %>
        <%= link_to t(:edit), edit_city_path(@city), :class => "btn btn-mini btn-primary pull-right" %>
      <% end %>

    </h4>
  </div>
</div>
<div class="row-fluid">

  <div class="span4">
    <p>
      <b>Name:</b>
      <%= @city.name %>
    </p>

    <p>
      <b>Latitude:</b>
      <%= @city.latitude %>
    </p>

    <p>
      <b>Longitude:</b>
      <%= @city.longitude %>
    </p>

    <p>
      <b>Radius (KM):</b>
      <%= @city.radius %>
    </p>

    <p>
      <b>Country code:</b>
      <%= @city.country_code %>
    </p>

    <p>
      <b>State province:</b>
      <%= @city.state_province %>
    </p>
  </div>

  <%= render 'cities/map' %>


</div>


<div class="form-actions">
  <%= link_to 'Back', cities_path, :class => 'btn' %>
</div>