config/routes.rb
require 'api'
Gohike::Application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    get "state_province_list", :to => "cities#states_or_provinces"

    get '/translation/:resource_type/:resource_id(/:target_locale)', :to => "translations#new", :as => :translation

    get "start", :to => "start#index"

    get "home", :to => "home#index"

    resources :routes do
      resource :reward
      member do
        put :waypoints
        get :crop
        put :publish
        put :unpublish
      end
    end
    resources :rewards
    resources :checkins

    resources :cities do
      resources :route_profiles
      resources :locations do
        collection do
          get :search
        end
      end
    end

    resources :route_profiles do
      collection do
        get :in_cities
      end
      member do
        get :crop
      end

    end
    resources :locations do
      member do
        get :crop
      end

    end
    resources :devices
    devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}

  end
  mount Gohike::API => "/api"

end

app/models/route_profile.rb
class RouteProfile < ActiveRecord::Base
  include ImageModel
  mount_uploader :image, RouteProfileImageUploader

  default_scope order('priority DESC')

  MIN_HEIGHT = 200
  MIN_WIDTH = 200

  attr_accessible :description, :image, :name, :translations_attributes,:city, :city_id, :priority

  belongs_to :city
  has_many :routes, :dependent => :destroy

  translates :name, :fallbacks_for_empty_translations => true
  accepts_nested_attributes_for :translations
  validates_presence_of :name
  after_update :crop_image
  validate :validate_minimum_image_size

  scope :in_cities, ->(city_ids) { where("city_id IN (?)", city_ids) }
  scope :in_city, ->(city_id) {
    where(:city_id => city_id)
  }

  def icon_data
    Base64.encode64(open(self.icon.to_s) { |io| io.read }) unless self.icon.to_s.blank?
  end


  class Translation
    attr_accessible :locale, :name
    validates_presence_of :name
  end

  def published_routes
    routes.where("published_key IS NOT NULL")
  end

end

app/controllers/route_profiles_controller.rb
class RouteProfilesController < InheritedResources::Base

  before_filter :authenticate_user!
  load_and_authorize_resource :city, :through => :route_profile
  load_and_authorize_resource :route_profile

  #defaults :singleton => true
  optional_belongs_to :city
  has_scope :in_city

  before_filter :load_routes, :only => :show

  def index
    super
  end

  def in_cities
    @profiles = RouteProfile.scoped_by_city_id(params[:city_ids])
    render :partial => "routes/profile"

  end

  # POST /route_profiles
  # POST /route_profiles.json
  def create
    create! do |success, failure|
      success.html {
        redirect_to params[:route_profile][:image].present? ? crop_route_profile_url(@route_profile) : route_profile_url(@route_profile)
      }
    end
  end


# PUT /route_profiles/1
# PUT /route_profiles/1.json
  def update
    update! do |success, failure|
      success.html {
        redirect_to params[:route_profile][:image].present? ? crop_route_profile_url(@route_profile) : route_profile_url(@route_profile)
      }
    end
  end

  private
  def load_routes
    @routes = @route_profile.routes
  end

end

app/helpers/route_profiles_helper.rb
module RouteProfilesHelper
end

app/views/route_profiles/_form.html.erb
<%= simple_form_for(@route_profile, :html => {:multipart => true}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs clearfix">

    <div class="span9">
      <%= f.association :city, :collection => cities_curated, :include_blank => false %>

      <%= f.input :priority, :input_html=>{ :min=>0, :max =>100} %>
      <%= f.input :image %>
    </div>
    <div class="span9">

      <%= render :partial => "shared/localized_attributes", :locals => {:resource => @route_profile, :f => f} %>

    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/route_profiles/_listing.html.erb
<div class="row-fluid">
  <%- model_class = RouteProfile -%>
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:translations) %></th>
      <th><%= model_class.human_attribute_name(:priority) %></th>
      <th></th>
    </tr>
    </thead>
    <% @route_profiles.each do |route_profile| %>
      <tr>
        <td><img src="<%= route_profile.image.icon %>" class="route-list-img"></td>
        <td class="name"><%= link_to route_profile.name, route_profile_path(route_profile) %></td>
        <td class="city"><%= route_profile.city.name unless route_profile.city.nil? %></td>
        <td class="translations"><%= route_profile.translated_locales.join(" | ") %></td>
        <td class="priority"><%= route_profile.priority %></td>
        <td><%= link_to t(:details), route_profile_path(route_profile), :class => "btn" %></td>
        <td><%= link_to t(:edit), edit_route_profile_path(route_profile), :class => "btn btn-primary" %></td>

      </tr>
    <% end %>
  </table>

</div>

app/views/route_profiles/crop.html.erb
<ul class="breadcrumb">
  <li><%= link_to t(:home) , home_path %> <span class="divider">/</span></li>
  <li><%= link_to t(:'navbar.route_profiles') , route_profiles_path %> <span class="divider">/</span></li>
  <li><%= link_to @route_profile.name , route_profile_path(@route_profile) %></li>
</ul>

<%= render 'shared/crop', :resource => @route_profile %>

app/views/route_profiles/edit.html.erb
<ul class="breadcrumb">
  <li><%= link_to t(:home) , home_path %> <span class="divider">/</span></li>
  <li><%= link_to t(:'navbar.route_profiles') , route_profiles_path %> <span class="divider">/</span></li>
  <li class="active"><%= t(:edit) + ' "' + @route_profile.name + '"'%></li>
</ul>

<%= render 'form' %>

<%= link_to 'Show', route_profiles_path() %> |
<%= link_to 'Back', route_profiles_path %>

app/views/route_profiles/index.html.erb
<ul class="breadcrumb">
  <li><%= link_to t(:home), home_path %><span class="divider">/</span></li>
  <% unless @city.nil? %>
    <li class=""><%= link_to t(:'navbar.cities') , cities_path %><span class="divider">/</span></li>
    <li class=""><%= link_to @city.name , city_path(@city) %><span class="divider">/</span></li>
  <% end %>
  <li class="active"><%= t(:'navbar.routes_profiles') %></li>
  <% if can? :create, RouteProfile %>
    <li class="pull-right"><%= link_to t(:add_profile), (@city.blank? ? new_route_profile_path : new_city_route_profile_path(@city)), :class => "add-route btn btn-mini btn-success pull-right" %></li>
  <% end %>
</ul>
<%= render :partial => "shared/city_tabs", :locals => {} %>
<%= render :partial => "route_profiles/listing", :locals => {} %>

app/views/route_profiles/new.html.erb
<ul class="breadcrumb">
  <li><%= link_to t(:home) , home_path %> <span class="divider">/</span></li>
  <li><%= link_to t(:'navbar.route_profiles') , route_profiles_path %> <span class="divider">/</span></li>
  <li class="active"><%=t(:new_route_profile) %></li>
</ul>

<%= render 'form' %>

<%= link_to 'Back', route_profiles_path %>

app/views/route_profiles/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to t(:home), home_path %> <span class="divider">/</span></li>
  <% unless @city.nil? %>
    <li class=""><%= link_to t(:'navbar.cities'), cities_path %>
      <span class="divider">/</span></li>
    <li class=""><%= link_to @city.name, city_path(@city) %>
      <span class="divider">/</span></li>
  <% end %>
  <li><%= link_to t(:'navbar.route_profiles'), route_profiles_path %> <span class="divider">/</span></li>
  <li class="active"><%= @route_profile.name %></li>
</ul>
<div class="row-fluid">

  <div class="span5">
    <h4><%= t :details %>
      <%= link_to t(:edit), edit_route_profile_path(@route_profile), :class => "btn btn-mini btn-primary pull-right" if can? :update, @route_profile %>
    </h4>
    <ul class="nav nav-tabs translations-tabs">
      <%= render :partial => "shared/translation_tabs", :locals => {:locale => I18n.locale, :resource => @route_profile, :active => true} %>
      <% @route_profile.translations.each do |translation| %>
        <%= render :partial => "shared/translation_tabs", :locals => {:locale => translation.locale, :resource => @route_profile} if (translation.locale != I18n.locale) %>
      <% end %>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active" id="<%= translation_tab_id(@route_profile, locale) %>">
        <h5><%= @route_profile.name %></h5>
      </div>
      <% @route_profile.translations.each do |translation| %>
        <%= render :partial => "shared/translation_values", :locals => {:translation => translation, :resource => @route_profile} %>
      <% end %>

    </div>
  </div>
  <div class="span5">
    <h4><%= t :icon %>
      <%= link_to t(:remove), @route_profile, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-mini btn-danger pull-right" if @route_profile.routes.empty? %>
      <%= link_to t(:crop), crop_route_profile_path(@route_profile), :class => "btn btn-mini pull-right" unless @route_profile.image.blank? %>
    </h4>
    <img style="width: 100px; height: 100px;" src="<%= @route_profile.image.icon %>?<%= Time.now.to_i %>">
  </div>
</div>
<h4><%= t(:"navbar.routes") %> </h4>
<%= render :partial => "routes/listing", :locals => {} %>