config/routes.rb
require 'api'
Gohike::Application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    get "state_province_list", :to => "cities#states_or_provinces"

    get '/translation/:resource_type/:resource_id(/:target_locale)', :to => "translations#new", :as => :translation

    get "start", :to => "start#index"

    get "home", :to => "home#index"

    resources :routes do
      resource :reward
      member do
        put :waypoints
        get :crop
        put :publish
        put :unpublish
      end
    end
    resources :rewards
    resources :checkins

    resources :cities do
      resources :route_profiles
      resources :locations do
        collection do
          get :search
        end
      end
    end

    resources :route_profiles do
      collection do
        get :in_cities
      end
      member do
        get :crop
      end

    end
    resources :locations do
      member do
        get :crop
      end

    end
    resources :devices
    devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}

  end
  mount Gohike::API => "/api"

end

app/models/location.rb
class Location < ActiveRecord::Base
  mount_uploader :image, LocationImageUploader
  acts_as_gmappable :process_geocoding => :geocode?
  include ImageModel

  attr_accessible :address, :city, :latitude, :longitude, :postal_code, :image, :name, :description, :city_id, :translations_attributes

  translates :name, :description, :fallbacks_for_empty_translations => true
  accepts_nested_attributes_for :translations, :allow_destroy => true

  has_many :waypoints
  has_many :routes, :through => :waypoints
  belongs_to :network, :class_name => "City", :foreign_key => :city_id

  scope :in_city, ->(city_id) {
    where(:city_id => city_id)
  }

  scope :in_cities, ->(city_ids) {
    where("city_id IN (?)", city_ids.split(","))
  }

  after_update :crop_image
  validates_presence_of :name, :description, :city_id,  :address, :city, :latitude, :longitude
  validate :validate_minimum_image_size
  validates_length_of :name, :maximum => 35
  validates_length_of :description, :maximum => 2048


  def geocode?
    (!address.blank? && (latitude.blank? || longitude.blank?))
  end

  def gmaps4rails_address
#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    "#{self.address},  #{self.postal_code} #{self.city}"
  end

  #def self.default_scope
  #
  #  #where published: true
  #end

  class Translation
    attr_accessible :locale, :name, :description
    validates_presence_of :name, :description
    validates_length_of :name, :maximum => 35
    validates_length_of :description, :maximum => 2048
  end


end

app/controllers/locations_controller.rb
class LocationsController < InheritedResources::Base
  layout Proc.new { |controller| (controller.request.xhr?) ? false : 'application' }
  before_filter :authenticate_user!
  before_filter :load_markers, :only => :show
  optional_belongs_to :city

  load_and_authorize_resource :city, :through => :location
  load_and_authorize_resource :location
  has_scope :in_city

  def load_markers
    @markers = resource.to_gmaps4rails
  end

  # POST /routes
  # POST /routes.json
  def create
    create! do |success, failure|
      success.html {
        if @location.id.blank?
          logger.info @location.errors
          #logger.info @location.errors
        end
        redirect_to params[:location][:image].present? ? crop_location_url(@location) : location_url(@location)
      }
    end
  end

  # PUT /routes/1
  # PUT /routes/1.json
  def update
    update! do |success, failure|
      success.html {
        redirect_to params[:location][:image].present? ? crop_location_url(@location) : location_url(@location)
      }
    end
  end

  def search
    @locations = @locations.where("id NOT IN (:exclude) AND (name ILIKE :term OR description ILIKE :term OR address ILIKE :term)", {:term => "%#{params[:term]}%", :exclude => params[:exclude].split(",")})
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= simple_form_for(@location) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs clearfix">


    <div class="span5">

      <%= f.input :network, :hint => @location.new_record? ? t(:".select_city_to_use_map") : nil do %>
        <%= f.select :city_id,
                     cities_curated.map { |a| [a.fullname, a.id, {:"data-latitude" => a.latitude, :"data-longitude" => a.longitude}] },
                     {include_blank: true},
                     {} %>
      <% end %>


      <%= f.input :image %>
      <%= f.input :address, :disabled => f.object.new_record?  %>
      <%= f.input :city, :disabled => f.object.new_record? %>
      <%= f.input :postal_code, :disabled => f.object.new_record? %>
      <%= f.input :latitude, :as => :string, :input_html => {:readonly => true} %>
      <%= f.input :longitude, :as => :string, :input_html => {:readonly => true} %>
    </div>
    <div class="span5">
      <%= search_field_tag :search_map, nil, :placeholder => t(:search_map), :class => "search-map", :disabled => f.object.new_record? %>
      <div class="location-map">

        <% options = {
            :map_options => {

                zoom: 14,
                auto_adjust: true,
                zoomControl: true,
                streetViewControl: false,
                scaleControl: false,
                rotateControl: false,
                mapTypeControl: false,
                panControl: false,
                scrollwheel: false,
                center_latitude: @location.latitude,
                center_longitude: @location.longitude

            },
            :markers => {:data => [], :options => {:do_clustering => true}}
        }
        %>
        <%= gmaps(options) %>
        <div class="overlay<%= " hidden" if f.object.persisted? %>"></div>
      </div>
    </div>
    <div class="span9">

      <%= render :partial => "shared/localized_attributes", :locals => {:resource => @location, :f => f} %>

    </div>


  </div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<% content_for :scripts do %>
  <script>

  </script>
<% end %>

app/views/locations/crop.html.erb
<ul class="breadcrumb">
  <li><%= link_to t(:home), home_path %> <span class="divider">/</span></li>
  <li><%= link_to t(:'navbar.locations'), locations_path %> <span class="divider">/</span></li>
  <li class="active"><%= link_to @location.name, location_path(@location) %></li>
</ul>

<%= render 'shared/crop', :resource => @location %>

app/views/locations/edit.html.erb
<ul class="breadcrumb">
  <li><%= link_to t(:home), home_path %> <span class="divider">/</span></li>
  <li><%= link_to t(:'navbar.locations'), locations_path %> <span class="divider">/</span></li>
  <li class="active"><%= @location.name %></li>
</ul>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<%- model_class = Location -%>
<ul class="breadcrumb">
  <li><%= link_to t(:home), home_path %> <span class="divider">/</span></li>
  <li class="active"><%= t(:'navbar.locations') %></li>
  <% if can? :create, Route %>
    <li class="pull-right"><%= link_to t(:add_location), new_location_path, :class => "add-location btn btn-mini btn-success pull-right" %></li>
  <% end %>
</ul>
<%= render :partial => "shared/city_tabs", :locals => {} %>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:image) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:address) %></th>
    <th><%= model_class.human_attribute_name(:postal_code) %></th>
    <th><%= model_class.human_attribute_name(:translations) %></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <% @locations.each do |location| %>
    <tr>
      <td><img src="<%= location.image.icon %>" class="route-list-img"></td>
      <td><%= location.name %></td>
      <td><%= location.address %></td>
      <td><%= location.postal_code %></td>
      <td><%= location.translated_locales.join(" | ") %></td>
      <td><%= link_to t(:details), location_path(location), :class => "btn btn-mini" %></td>
      <td><%= if can? :update, location
                link_to t(:edit), edit_location_path(location), :class => "btn btn-mini btn-primary"
              end %></td>

    </tr>
  <% end %>
</table>

<br/>

app/views/locations/new.html.erb
<%- model_class = Location -%>
<ul class="breadcrumb">
  <li><%= link_to t(:home), home_path %> <span class="divider">/</span></li>
  <li><%= link_to t(:'navbar.locations'), locations_path %> <span class="divider">/</span></li>
  <li class="active"><%= t(:".title") %></li>
</ul>
<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/search.html.erb
<% @locations.each do |location| %>
  <li class="ui-state-default alert-info" data-location-id="<%= location.id %>">
    <%= render :partial => "routes/waypoint", :locals => {:location => location} %>
  </li>
<% end %>

app/views/locations/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to t(:home), home_path %> <span class="divider">/</span></li>
  <li><%= link_to t(:'navbar.locations'), locations_path %> <span class="divider">/</span></li>
  <li class="active"><%= @location.name %></li>
</ul>
<div class="row-fluid">

  <div class="span5">
    <h4><%= t :details %>
      <%= link_to t(:edit), edit_location_path(@location), :class => "btn btn-mini btn-primary pull-right" if can? :edit, @location%>
    </h4>
    <ul class="nav nav-tabs translations-tabs">
      <%= render :partial => "shared/translation_tabs", :locals => {:locale => I18n.locale, :resource => @location, :active => true} %>
      <% @location.translations.each do |translation| %>
        <%= render :partial => "shared/translation_tabs", :locals => {:locale => translation.locale, :resource => @location} if (translation.locale != I18n.locale) %>
      <% end %>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active" id="<%= translation_tab_id(@location, locale) %>">

        <h5><%= @location.name %></h5>

        <p><%= @location.description %></p>
      </div>
      <% @location.translations.each do |translation| %>
        <%= render :partial => "shared/translation_values", :locals => {:translation => translation, :resource => @location} %>
      <% end %>

    </div>
  </div>
  <div class="span5">
    <h4><%= t :image %>

      <%= link_to t(:remove), @location, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-mini btn-danger pull-right" if @location.waypoints.empty? && can?(:destroy, @location)%>
      <%= link_to t(:crop), crop_location_path(@location), :class => "btn btn-mini pull-right" if @location.image.present? && can?(:crop, @location)  %>
    </h4>
    <img style="width: 285px; height: 190px;" src="<%= @location.image.mobile %>?<%= Time.now.to_i %>">
  </div>
</div>
<div class="row-fluid">

  <div class="span5">
    <h4><%= t :address_and_coordinates %></h4>

    <p>
      <b>Address:</b>
      <%= @location.address %>
    </p>

    <p>
      <b>City:</b>
      <%= @location.city %>
    </p>

    <p>
      <b>Postal code:</b>
      <%= @location.postal_code %>
    </p>

    <p>
      <b>Latitude:</b>
      <%= @location.latitude %>
    </p>

    <p>
      <b>Longitude:</b>
      <%= @location.longitude %>
    </p>
  </div>
  <div class="span4">
    <h4><%= t :map %></h4>
    <% options = {
        :map_options => {
            :auto_adjust => false,
            zoomControl: true,
            zoom: 16,
            streetViewControl: false,
            scaleControl: false,
            rotateControl: false,
            mapTypeControl: false,
            panControl: false,
            center_latitude: @location.latitude,
            center_longitude: @location.longitude

        },
        :markers => {:data => @markers, :options => {:do_clustering => true}}
    }
    %>
    <%= gmaps(options) %>
  </div>
</div>